[package]
name = "token-bindings-test"
version = "0.9.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>", "Jake Hartnell <no-reply@no-reply.com>"]
edition = "2021"
description = "Multitest (and other test helpers) support for Token factory contracts"
repository = "https://github.com/CosmosContracts/token-bindings"
license = "Apache-2.0"

[dependencies]
itertools = "0.11"
token-bindings = { version = "0.11.0", path = "../bindings" }
cosmwasm-std = "1.1"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
# TODO use upstream when PR merged: https://github.com/CosmWasm/cw-multi-test/pull/51
cw-multi-test = { git = "https://github.com/JakeHartnell/cw-multi-test.git", branch = "bank-supply-support" }
cw-storage-plus = "0.16"
anyhow = "1"
thiserror = "1.0"
